# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the Foretoken project

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../quickstart
patches:
  - path: observability.yaml
  # Keep the base deployment's data directory when using this overlay.
  - target:
      kind: RuntimeCache
      name: models
    patch: |-
      - op: replace
        path: /spec/directory
        value: ../quickstart/data
